# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '\u6559\u5e08', 'verbose_name_plural': '\u6559\u5e08'},
        ),
    ]
