# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20180724_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', max_length=200, upload_to='teacher/%Y/%m', verbose_name='\u5934\u50cf'),
        ),
    ]
