# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 00:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_course_category'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='name',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='\u8bfe\u7a0b\u540d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercourse',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u59d3\u540d'),
            preserve_default=False,
        ),
    ]
