# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20180728_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.IntegerField(max_length=100, verbose_name='\u5b66\u751f\u4eba\u6570'),
        ),
    ]
