# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-08 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180807_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u8f6e\u64ad'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.IntegerField(verbose_name='\u5b66\u751f\u4eba\u6570'),
        ),
    ]
